# Generated by Django 4.2.2 on 2023-06-22 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=45)),
                ('file_author', models.CharField(max_length=45)),
                ('file_description', models.CharField(max_length=250)),
                ('file_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files/')),
                ('file_submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
