# Generated by Django 4.2.2 on 2023-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='file_image/'),
        ),
    ]
