# Generated by Django 4.2.2 on 2023-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0003_file_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sas_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='sas_url',
            field=models.URLField(blank=True),
        ),
    ]
