# Generated by Django 4.2.2 on 2023-06-23 13:28

from django.db import migrations, models
import tesapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0004_file_sas_url_photo_sas_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=tesapp.models.generate_upload_path),
        ),
    ]
