# Generated by Django 4.2.2 on 2023-08-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0008_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
