# Generated by Django 4.2.2 on 2023-08-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='sas_url',
        ),
    ]
